name: Mirror and Scan 3proxy

on:
  push:
    branches: ["master"]

jobs:
  mirror:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull official image
        run: docker pull tarampampam/3proxy:latest

      - name: Scan with Trivy
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: tarampampam/3proxy:latest
          severity: HIGH,CRITICAL
          exit-code: '1'   # если найдёт HIGH/CRITICAL — job упадёт, push не выполнится

      - name: Retag and push to GHCR
        run: |
          docker tag tarampampam/3proxy:latest ghcr.io/yabloky/3proxy:latest
          docker push ghcr.io/yabloky/3proxy:latest
